name:                linkedgram
version:             0.1.0.0
#synopsis:
description:         Please see README.md
homepage:            https://github.com/Junology/linkedgram#readme
license:             BSD3
author:              Jun Yoshida
maintainer:          migi.hineri.jun@gmail.com
copyright:           2019 Jun Yoshida
category:            Education
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - containers
  - monad-loops
  - parallel
  - deepseq
  - vector
  - text
  - matrix
  - hmatrix
  - directory
  - gtk3
  - cairo

executables:
  linkedgram:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -O
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -DPROJECT_NAME="linkedgram"
    - -DPROJECT_VERSION="0.1.0.0"
    - -DPROJECT_AUTHOR_GIVEN="Jun"
    - -DPROJECT_AUTHOR_FAMILY="Yoshida"
    - -DPROJECT_COPYRIGHT_YEAR="2019"
    - -DPROJECT_LICENSE="BSD3"
    - -DPROJECT_HOMEPAGE="https://github.com/Junology/linkedgram#readme"
    c-sources:
    - src/Numeric/Algebra/IntMatrix/HermiteNFLLL.c
    cc-options: -O3 -fopenmp -march=native
    ld-options: -O3
    extra-libraries:
    - omp
    - m

benchmarks:
  linkedgram-bench:
    source-dirs:
    - benchmark
    - src
    other-modules:
    - Numeric.Algebra.FreeModule
    - Numeric.Algebra.Frobenius
    - Numeric.Algebra.IntMatrix
    - Numeric.Algebra.IntMatrix.HNFLLL
    - Numeric.Algebra.IntMatrix.HermiteNFLLL
    - Numeric.Algebra.IntMatrix.SmithNF
    - ArcGraph
    - ArcGraph.EnhancedState
    main:           BenchMain.hs
    dependencies:
    - criterion
    ghc-options:
    - -O
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    c-sources:
    - src/Numeric/Algebra/IntMatrix/HermiteNFLLL.c
    cc-options: -O3 -fopenmp -march=native
    ld-options: -O3
    extra-libraries:
    - omp
    - m
