name:                linkedgram
version:             0.1.0.0
#synopsis:
description:         Please see README.md
homepage:            https://github.com/Junology/linkedgram#readme
license:             BSD3
author:              Jun Yoshida
maintainer:          migi.hineri.jun@gmail.com
copyright:           2019 Jun Yoshida
category:            Education
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - containers
  - monad-loops
  - vector
  - text
  - matrix
  - hmatrix
  - directory
  - gtk3
  - cairo

executables:
  linkedgram:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -DPROJECT_NAME="linkedgram"
    - -DPROJECT_VERSION="0.1.0.0"
    - -DPROJECT_AUTHOR_GIVEN="Jun"
    - -DPROJECT_AUTHOR_FAMILY="Yoshida"
    - -DPROJECT_COPYRIGHT_YEAR="2019"
    - -DPROJECT_LICENSE="BSD3"
    - -DPROJECT_HOMEPAGE="https://github.com/Junology/linkedgram#readme"
